language: java
jdk:
- oraclejdk8
deploy:
  provider: s3
  access_key_id: AKIAJRXSZUVEN6MH27RQ
  secret_access_key:
    secure: ZW8vbcCURyyQJSZYVc7E9SWw4QsO3HcLPZNujRgpxG6OTdzthQ9DbGZ30G4cpTQT6c08GZ3YThlBHsLUgqh2nwNiBRMTEt+PO5e5nliUIUZQSqTkKGtF0/Voz1+TAm0Nt5dFRj2uSBnqSmZUzn/32Q6PalCjG19NK0EKkA2op3danfejt68FoFSBesEjSpaOlnbOg1xKYEYmS7+zdS7Z9yGQp1dyzIJYxLyswZDV7MV3XgdBgShyOhsS4Nv4ylvaNlCkj/CYrHuVFDnLpI2RlUZLzgghhbicrghHmLotIHqAxlL2cSZutsB8IotTH5plpbYTRsdi9fnWGwZ6Z7HsLT1VryEbsaDx3W6ivqyZxVMwDGJtun/1jbMzggvG16pgwnamFPj+ryZuIMvwrdsr6hV/iyWgrp06DfLPUoT04rQwrUixCxxegzgi5Ke1lJBAyQJq/Pd1PRjloRxGf3aE9PVaToEIYpf+EMyjysx6PKvDn8t0I5hX5SqudveR7fYnRj2KYbjmotcpMn2UsWNGhutp2KjZDIlFHvcTJoX7nVdPf4g+yHbxKDuoPFvWE8p4i9nZoKCcGMlWdQpEnqVHSqLq/CbAXWGeBH5Pe2nuBWM+HLSPtFIA1g1dnoWGzFnp36InSU1pWGRR1O+wFFjhn7u7CrQGM6GJ2IWisFmSC28=
  bucket: deploy.then.to
  acl: public_read
  local_dir: build
  on:
    repo: then-to/to-slack
